vich_uploader:
    db_driver: orm

    mappings:
        picture_image:
            uri_prefix: /uploads/pictures
            upload_destination: '%kernel.project_dir%/public/uploads/pictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
